### ISSUE TITLE
Create identity

### ISSUE THREAD

**Issue by rosarp** [go-bazzinga/hot-or-not-auth#3]
Setup Axum server.
Create basic & delegate identity on server.

**Comment by rosarp-gobazzinga** [comment]
### API Details: 

#### POST /generate_session

#### BODY: application/json
```rust
struct SessionRequest {
    user_identity: Option<String>,
}
```

#### Description: 

To generate session for first time user. user_identity need not be passed. 
This api can be used to renew session if user_identity is passed. 

#### Response: application/json

```rust
struct SessionResponse {
    user_identity: String,
    delegation_identity: DelegationIdentity {
        _inner: Vec<Vec<u8>>,
        _delegation: DelegationChain {
            delegations: Vec<SignedDelegation {
                delegation: Delegation {
                    pubkey: Vec<u8>,
                    expiration: String,
                    targets: Option<Vec<String>>
                }
                signature: Vec<u8>
            }>
            publicKey: Vec<u8>
        }
    }
}
```

**Comment by rosarp-gobazzinga** [comment]
Raised PR with this api. #7

**Comment by rosarp-gobazzinga** [comment]
Change user_identity to some signature with expiration.
Remove from json payload, put in http cookie.
Page redirect:
- need to pass renewed delegated_identity
- New user_identity signature

To Check: 
post message API.
