### ISSUE TITLE
Test identity against principal

### ISSUE THREAD

**Issue by rosarp** [go-bazzinga/hot-or-not-auth#4]
Setup new canister.
Receive identity from axum server and return back principal.

Purpose: To test if delegate identity can be used to get identified as same principal on canister.

**Comment by rosarp-gobazzinga** [comment]
I have generated Identity on server (axum) for incoming user.
Using that identity and server's own 'Identity',
I'm trying to create delegated identity, on the server. 
And I want to use this Delegated Identity from browser, for the user to connect to a canister.

Below is the code for `Axum server` : [Server side code](https://github.com/go-bazzinga/hot-or-not-auth/blob/7695b4ebf4012fa0b5647f2e04d0a00b42649f48/src/main.rs#L24)


`Client Identity` Code:
```
    let (client_secret, _client_pem) = generate_key("oauth_identity").unwrap();
    let client_identity = Secp256k1Identity::from_private_key(client_secret.clone());
```
`Server Identity` Code:
```
    let path = Path::new(SERVER_PEM_FILEPATH);
    let server_identity = Secp256k1Identity::from_pem_file(path).unwrap();
```
Creating `Delegated Identity`:
```
....
    let delegation = Delegation {
        pubkey: server_identity.public_key().unwrap(),
        expiration,
        targets: None,
    };
....
    let signature = client_identity.sign_delegation(&delegation).unwrap();
    let signed_delegation = SignedDelegation {
        delegation,
        signature: signature.signature.unwrap(),
    };
....
    let delegated_identity = DelegatedIdentity::new(
        signature.public_key.unwrap(),
        server_identity,
        vec![signed_delegation.clone()],
    );
```

Here I can send to browser, serialized `signed_delegation`. However `delegated_identity` is not serializable.
-> Which means, using the signed_delegation, I need to create identity on the browser again. Need help with this, as I see either the approach is not feasible or I'm missing something.

Code on `browser` side: [Frontend code](https://github.com/go-bazzinga/hot-or-not-auth/blob/7695b4ebf4012fa0b5647f2e04d0a00b42649f48/verify_principal/src/verify_principal_frontend/src/index.js#L40)
```
import { verify_principal_backend } from "../../declarations/verify_principal_backend";
import { DelegationIdentity, DelegationChain } from "@dfinity/identity";
....
const delegationChain = DelegationChain.fromJSON(signed_delegation);
// below method needs a identity, will it be newly generated identity?
const clientIdentity = Secp256k1KeyIdentity.generate();                                                                  
const delegatedIdentity = DelegationIdentity.fromDelegation(clientIdentity, delegationChain);
// call to canister
await verify_principal_backend.get_principal_id();
```
With above code, there is error: `Invalid delegations. ` on below line:
```
const delegationChain = DelegationChain.fromJSON(signed_delegation);
```

Here above, as there is no identity coming from server, clientIdentity needs to be creatd on browser side to create delegated identity. Is there any way to create delegated identity on server and pass it for usage to browser? 

cc: @saikatdas0790

**Comment by saikatdas0790** [comment]
Looks like a decent explanation of the problem you're running into.

It might also be a good idea to explain the problem you're trying to solve, i.e., being able to make requests on behalf of the user from the server and from the user's browser using the same principal..

**Comment by rosarp-gobazzinga** [comment]
Issue resolved.
Changes are committed under examples/verify-auth-solidjs
 PR raised #7
