### ISSUE TITLE
anonymous identity doesn't work on localhost

### ISSUE THREAD

**Issue by rupansh-sekar-yral** [go-bazzinga/hot-or-not-auth#76]
https://github.com/go-bazzinga/hot-or-not-auth/blob/main/src/page/anonymous.rs#L23
anonymous identity page only sends message to the main app

Please consider using feature flags for production & dev environments, and enabling dev feature for now
ideally we should deploy separate auth sites for prod & dev

**Comment by rosarp-gobazzinga** [comment]
We can discuss this in call. So, constants have this value which can be changed for perticular deployment. 
If you start server locally, then you can change here : https://github.com/go-bazzinga/hot-or-not-auth/blob/13071bb57da17dff4cb1de644f37bb139571e723/src/constants.rs#L7

**Comment by rosarp-gobazzinga** [comment]
Pushed code to main in PR #75
